# Write a program to print Twinkle Twinkle Little Start poem.

print("Twinkle, twinkle, little star,")
print("How I wonder what you are!")
print("Up above the world so high,")
print("Like a diamond in the sky.")
print("Twinkle, twinkle, little star,")
print("How I wonder what you are!")
print("When the blazing sun is gone,")
print("When he nothing shines upon,")
print("Then you show your little light,")
print("Twinkle, twinkle, all the night.")
print("Twinkle, twinkle, little star,")
print("How I wonder what you are!")
print("Then the traveler in the dark")
print("Thanks you for your tiny spark;")
print("He could not see which way to go,")
print("If you did not twinkle so.")
print("Twinkle, twinkle, little star,")
print("How I wonder what you are!")
print("In the dark blue sky you keep,")
print("And often through my curtains peep,")
print("For you never shut your eye")
print("Till the sun is in the sky.")
print("As your bright and tiny spark")
print("Lights the traveler in the dark,")
print("Though I know not what you are,")
print("Twinkle, twinkle, little star.")
print("Twinkle, twinkle, little star,")
